import Foundation

package enum Strings {
    package static func text(_ key: String, locale: String, args: [String: String] = [:]) -> String {
        let bundle = bundles[locale] ?? bundles["en-US"]!
        var value = bundle[key] ?? bundles["en-US"]![key] ?? key
        for (placeholder, replacement) in args {
            value = value.replacingOccurrences(of: "{{\(placeholder)}}", with: replacement)
        }
        return value
    }

    package static func submitButtonTitle(type: String, locale: String, amount: String?) -> String {
        let key = "button.\(type)"
        if let amount, !amount.isEmpty {
            return text(key, locale: locale, args: ["amount": amount])
        }
        return text(key.replacingOccurrences(of: ".pay", with: ".payNoAmount"), locale: locale)
    }

    package static func formatAmount(_ amount: Double?, currency: String?) -> String? {
        guard let amount else { return nil }
        let formatter = NumberFormatter()
        formatter.numberStyle = .currency
        formatter.currencyCode = currency ?? "EUR"
        return formatter.string(from: NSNumber(value: amount))
    }

    private static let bundles: [String: [String: String]] = [
        "en-US": en,
        "el-GR": el,
        "ro-RO": ro,
    ]

    private static let en: [String: String] = [
        "sheet.title": "Payment",
        "sheet.cancel": "Cancel",
        "sheet.creditDebitCard": "Credit / Debit Card",
        "sheet.poweredBy": "Powered by",
        "sheet.savedCards": "Saved cards",
        "sheet.payingWith": "Paying with",
        "sheet.useAnotherCard": "Use another card",
        "sheet.useOtherCard": "Use other card",
        "sheet.or": "or",
        "sheet.cardDetails": "Card details",
        "sheet.enterCardDetails": "Enter card details",
        "sheet.visaOrMastercard": "Visa or Mastercard",
        "sheet.cardBrandsHint": "Visa or Mastercard",
        "sheet.saveCardShort": "Save card for next time",
        "sheet.delete": "Delete",
        "sheet.edit": "Edit",
        "sheet.done": "Done",
        "sheet.removeCardConfirm": "Are you sure you want to remove this card?",
        "sheet.remove": "Remove",
        "sheet.keepIt": "Keep it",
        "sheet.default": "Default",
        "sheet.authentication": "Authentication",
        "sheet.processingPayment": "Processing your payment...",
        "elements.cardNumber": "Card Number",
        "elements.cardholderName": "Cardholder Name",
        "elements.expDate": "Expiration Date",
        "elements.cvv": "CVV",
        "elements.saveCard": "Save Card for Future Use",
        "elements.saveCardShort": "Save card for next time",
        "placeholder.cardNumber": "0000 - 0000 - 0000 - 0000",
        "placeholder.expDate": "MM / YY",
        "placeholder.cvv": "000",
        "placeholder.cardholderName": "Cardholder name",
        "errors.cardNumberRequired": "Card number is required.",
        "errors.cardNumberUnsupported": "Card type is not supported.",
        "errors.cardNumberTooShort": "Card number is too short.",
        "errors.cardNumberWrongLength": "Card number length is invalid.",
        "errors.cardNumberInvalid": "Card number is invalid.",
        "errors.expDateRequired": "Expiration date is required.",
        "errors.expDateInvalidFormat": "Expiration date format is invalid.",
        "errors.expDateInvalidMonth": "Expiration month is invalid.",
        "errors.cardExpired": "Card is expired.",
        "errors.cvvRequired": "CVV is required.",
        "errors.cvvInvalid": "CVV is invalid.",
        "errors.cardHolderNameRequired": "Cardholder name is required.",
        "errors.cardHolderNameNoDigits": "The cardholder name cannot contain numbers.",
        "errors.cardHolderNameInvalidChars": "Only letters, spaces, apostrophes, hyphens, and periods are allowed.",
        "button.pay": "Pay {{amount}}",
        "button.payNoAmount": "Pay",
        "button.processing": "Processing...",
        "button.book": "Book {{amount}}",
        "button.buy": "Buy {{amount}}",
        "button.checkout": "Checkout {{amount}}",
        "button.donate": "Donate {{amount}}",
        "button.order": "Place order {{amount}}",
        "button.subscribe": "Subscribe for {{amount}}",
        "button.topUp": "Top up {{amount}}",
        "button.deposit": "Deposit {{amount}}",
    ]

    private static let el: [String: String] = [
        "sheet.title": "Πληρωμή",
        "sheet.cancel": "Ακύρωση",
        "sheet.creditDebitCard": "Πιστωτική / Χρεωστική κάρτα",
        "sheet.poweredBy": "Με την υποστήριξη",
        "sheet.savedCards": "Αποθηκευμένες κάρτες",
        "sheet.payingWith": "Πληρωμή με",
        "sheet.useAnotherCard": "Χρήση άλλης κάρτας",
        "sheet.useOtherCard": "Χρήση άλλης κάρτας",
        "sheet.or": "ή",
        "sheet.cardDetails": "Στοιχεία κάρτας",
        "sheet.enterCardDetails": "Εισαγάγετε στοιχεία κάρτας",
        "sheet.visaOrMastercard": "Visa ή Mastercard",
        "sheet.cardBrandsHint": "Visa ή Mastercard",
        "sheet.saveCardShort": "Αποθήκευση κάρτας για επόμενη φορά",
        "sheet.delete": "Διαγραφή",
        "sheet.edit": "Επεξεργασία",
        "sheet.done": "Τέλος",
        "sheet.removeCardConfirm": "Είστε βέβαιοι ότι θέλετε να αφαιρέσετε αυτή την κάρτα;",
        "sheet.remove": "Αφαίρεση",
        "sheet.keepIt": "Διατήρηση",
        "sheet.default": "Προεπιλογή",
        "sheet.authentication": "Ταυτοποίηση",
        "sheet.processingPayment": "Επεξεργασία πληρωμής...",
        "elements.cardNumber": "Αριθμός κάρτας",
        "elements.cardholderName": "Όνομα κατόχου",
        "elements.expDate": "Ημερομηνία λήξης",
        "elements.cvv": "CVV",
        "elements.saveCard": "Αποθήκευση κάρτας για μελλοντική χρήση",
        "elements.saveCardShort": "Αποθήκευση κάρτας για επόμενη φορά",
        "placeholder.cardNumber": "0000 - 0000 - 0000 - 0000",
        "placeholder.expDate": "ΜΜ / ΕΕ",
        "placeholder.cvv": "000",
        "placeholder.cardholderName": "Όνομα κατόχου",
        "errors.cardNumberRequired": "Ο αριθμός κάρτας είναι υποχρεωτικός.",
        "errors.cardNumberUnsupported": "Ο τύπος κάρτας δεν υποστηρίζεται.",
        "errors.cardNumberTooShort": "Ο αριθμός κάρτας είναι πολύ σύντομος.",
        "errors.cardNumberWrongLength": "Το μήκος του αριθμού κάρτας δεν είναι έγκυρο.",
        "errors.cardNumberInvalid": "Ο αριθμός κάρτας δεν είναι έγκυρος.",
        "errors.expDateRequired": "Η ημερομηνία λήξης είναι υποχρεωτική.",
        "errors.expDateInvalidFormat": "Η μορφή της ημερομηνίας λήξης δεν είναι έγκυρη.",
        "errors.expDateInvalidMonth": "Ο μήνας λήξης δεν είναι έγκυρος.",
        "errors.cardExpired": "Η κάρτα έχει λήξει.",
        "errors.cvvRequired": "Το CVV είναι υποχρεωτικό.",
        "errors.cvvInvalid": "Το CVV δεν είναι έγκυρο.",
        "errors.cardHolderNameRequired": "Το όνομα κατόχου είναι υποχρεωτικό.",
        "errors.cardHolderNameNoDigits": "Το όνομα κατόχου δεν μπορεί να περιέχει αριθμούς.",
        "errors.cardHolderNameInvalidChars": "Επιτρέπονται μόνο γράμματα, κενά, απόστροφοι, παύλες και τελείες.",
        "button.pay": "Πληρωμή {{amount}}",
        "button.payNoAmount": "Πληρωμή",
        "button.processing": "Επεξεργασία...",
        "button.book": "Κράτηση {{amount}}",
        "button.buy": "Αγορά {{amount}}",
        "button.checkout": "Ολοκλήρωση {{amount}}",
        "button.donate": "Δωρεά {{amount}}",
        "button.order": "Παραγγελία {{amount}}",
        "button.subscribe": "Συνδρομή {{amount}}",
        "button.topUp": "Φόρτιση {{amount}}",
        "button.deposit": "Κατάθεση {{amount}}",
    ]

    private static let ro: [String: String] = [
        "sheet.title": "Plată",
        "sheet.cancel": "Anulează",
        "sheet.creditDebitCard": "Card de credit / debit",
        "sheet.poweredBy": "Oferit de",
        "sheet.savedCards": "Carduri salvate",
        "sheet.payingWith": "Plată cu",
        "sheet.useAnotherCard": "Folosește alt card",
        "sheet.useOtherCard": "Folosește alt card",
        "sheet.or": "sau",
        "sheet.cardDetails": "Detalii card",
        "sheet.enterCardDetails": "Introduceți detaliile cardului",
        "sheet.visaOrMastercard": "Visa sau Mastercard",
        "sheet.cardBrandsHint": "Visa sau Mastercard",
        "sheet.saveCardShort": "Salvează cardul pentru data viitoare",
        "sheet.delete": "Șterge",
        "sheet.edit": "Editează",
        "sheet.done": "Gata",
        "sheet.removeCardConfirm": "Sigur doriți să eliminați acest card?",
        "sheet.remove": "Elimină",
        "sheet.keepIt": "Păstrează",
        "sheet.default": "Implicit",
        "sheet.authentication": "Autentificare",
        "sheet.processingPayment": "Se procesează plata...",
        "elements.cardNumber": "Număr card",
        "elements.cardholderName": "Numele titularului",
        "elements.expDate": "Data expirării",
        "elements.cvv": "CVV",
        "elements.saveCard": "Salvează cardul pentru utilizări viitoare",
        "elements.saveCardShort": "Salvează cardul pentru data viitoare",
        "placeholder.cardNumber": "0000 - 0000 - 0000 - 0000",
        "placeholder.expDate": "LL / AA",
        "placeholder.cvv": "000",
        "placeholder.cardholderName": "Numele titularului",
        "errors.cardNumberRequired": "Numărul cardului este obligatoriu.",
        "errors.cardNumberUnsupported": "Tipul de card nu este acceptat.",
        "errors.cardNumberTooShort": "Numărul cardului este prea scurt.",
        "errors.cardNumberWrongLength": "Lungimea numărului de card este invalidă.",
        "errors.cardNumberInvalid": "Numărul cardului este invalid.",
        "errors.expDateRequired": "Data expirării este obligatorie.",
        "errors.expDateInvalidFormat": "Formatul datei de expirare este invalid.",
        "errors.expDateInvalidMonth": "Luna de expirare este invalidă.",
        "errors.cardExpired": "Cardul a expirat.",
        "errors.cvvRequired": "CVV-ul este obligatoriu.",
        "errors.cvvInvalid": "CVV-ul este invalid.",
        "errors.cardHolderNameRequired": "Numele titularului este obligatoriu.",
        "errors.cardHolderNameNoDigits": "Numele titularului nu poate conține cifre.",
        "errors.cardHolderNameInvalidChars": "Sunt permise doar litere, spații, apostroafe, cratime și puncte.",
        "button.pay": "Plătește {{amount}}",
        "button.payNoAmount": "Plătește",
        "button.processing": "Se procesează...",
        "button.book": "Rezervă {{amount}}",
        "button.buy": "Cumpără {{amount}}",
        "button.checkout": "Finalizează {{amount}}",
        "button.donate": "Donează {{amount}}",
        "button.order": "Comandă {{amount}}",
        "button.subscribe": "Abonare {{amount}}",
        "button.topUp": "Alimentează {{amount}}",
        "button.deposit": "Depune {{amount}}",
    ]
}
