import Foundation

package enum Strings {
    package static func text(_ key: String, locale: String, args: [String: String] = [:]) -> String {
        let catalog = resolvedCatalog(for: locale)
        var value = catalog[key] ?? catalogs["en"]![key] ?? key
        for (placeholder, replacement) in args {
            value = value.replacingOccurrences(of: "{{\(placeholder)}}", with: replacement)
        }
        return value
    }

    package static func submitButtonTitle(type: String, locale: String, amount: String?) -> String {
        let key = "button.\(type)"
        if let amount, !amount.isEmpty {
            return text(key, locale: locale, args: ["amount": amount])
        }
        return text(key.replacingOccurrences(of: ".pay", with: ".payNoAmount"), locale: locale)
    }

    package static func formatAmount(_ amount: Double?, currency: String?, locale: String = "en-US") -> String? {
        guard let amount else { return nil }
        let formatter = NumberFormatter()
        formatter.numberStyle = .currency
        formatter.locale = Locale(identifier: locale)
        formatter.currencyCode = currency ?? "EUR"
        return formatter.string(from: NSNumber(value: amount))
    }

    package static func catalogKeys(for locale: String) -> Set<String> {
        Set(resolvedCatalog(for: locale).keys)
    }

    private static func resolvedCatalog(for locale: String) -> [String: String] {
        if let exact = catalogs[locale] {
            return exact
        }
        let language = locale.split(separator: "-").first.map(String.init) ?? locale
        return catalogs[language] ?? catalogs["en"]!
    }

    private static let catalogs: [String: [String: String]] = [
        "en": en,
        "en-US": en,
        "el": el,
        "el-GR": el,
        "ro": ro,
        "ro-RO": ro,
        "bg": bg,
        "bg-BG": bg,
        "hu": hu,
        "hu-HU": hu,
        "pl": pl,
        "pl-PL": pl,
    ]

    private static let en: [String: String] = [
        "sheet.title": "Payment",
        "sheet.cancel": "Cancel",
        "sheet.creditDebitCard": "Credit / Debit Card",
        "sheet.poweredBy": "Powered by",
        "sheet.savedCards": "Saved cards",
        "sheet.payingWith": "Paying with",
        "sheet.useAnotherCard": "Use another card",
        "sheet.useOtherCard": "Use other card",
        "sheet.or": "or",
        "sheet.cardDetails": "Card details",
        "sheet.enterCardDetails": "Enter card details",
        "sheet.visaOrMastercard": "Visa or Mastercard",
        "sheet.cardBrandsHint": "Visa or Mastercard",
        "sheet.saveCardShort": "Save card for next time",
        "sheet.delete": "Delete",
        "sheet.edit": "Edit",
        "sheet.done": "Done",
        "sheet.removeCardConfirm": "Are you sure you want to remove this card?",
        "sheet.remove": "Remove",
        "sheet.keepIt": "Keep it",
        "sheet.default": "Default",
        "sheet.authentication": "Authentication",
        "sheet.processingPayment": "Processing your payment...",
        "elements.cardNumber": "Card Number",
        "elements.cardholderName": "Cardholder Name",
        "elements.expDate": "Expiration Date",
        "elements.cvv": "CVV",
        "elements.saveCard": "Save Card for Future Use",
        "elements.saveCardShort": "Save card for next time",
        "placeholder.cardNumber": "Card number",
        "placeholder.cardNumber.spaced": "1234 1234 1234 1234",
        "placeholder.expDate": "MM / YY",
        "placeholder.cvv": "CVV",
        "placeholder.cvv.spaced": "123",
        "placeholder.cardholderName": "Name on card",
        "errors.cardNumberRequired": "Card number is required.",
        "errors.cardNumberUnsupported": "Card type is not supported.",
        "errors.cardNumberTooShort": "Card number is too short.",
        "errors.cardNumberWrongLength": "Card number length is invalid.",
        "errors.cardNumberInvalid": "Card number is invalid.",
        "errors.expDateRequired": "Expiration date is required.",
        "errors.expDateInvalidFormat": "Expiration date format is invalid.",
        "errors.expDateInvalidMonth": "Expiration month is invalid.",
        "errors.cardExpired": "Card is expired.",
        "errors.cvvRequired": "CVV is required.",
        "errors.cvvInvalid": "CVV is invalid.",
        "errors.cardHolderNameRequired": "Cardholder name is required.",
        "errors.cardHolderNameNoDigits": "The cardholder name cannot contain numbers.",
        "errors.cardHolderNameInvalidChars":
            "Only letters, spaces, apostrophes, hyphens, and periods are allowed.",
        "button.pay": "Pay {{amount}}",
        "button.payNoAmount": "Pay",
        "button.processing": "Processing...",
        "button.book": "Book {{amount}}",
        "button.buy": "Buy {{amount}}",
        "button.checkout": "Checkout {{amount}}",
        "button.donate": "Donate {{amount}}",
        "button.order": "Place order {{amount}}",
        "button.subscribe": "Subscribe for {{amount}}",
        "button.topUp": "Top up {{amount}}",
        "button.deposit": "Deposit {{amount}}",
    ]

    private static let el: [String: String] = [
        "sheet.title": "Πληρωμή",
        "sheet.cancel": "Ακύρωση",
        "sheet.creditDebitCard": "Πιστωτική / Χρεωστική κάρτα",
        "sheet.poweredBy": "Με την υποστήριξη",
        "sheet.savedCards": "Αποθηκευμένες κάρτες",
        "sheet.payingWith": "Πληρωμή με",
        "sheet.useAnotherCard": "Χρήση άλλης κάρτας",
        "sheet.useOtherCard": "Χρήση άλλης κάρτας",
        "sheet.or": "ή",
        "sheet.cardDetails": "Στοιχεία κάρτας",
        "sheet.enterCardDetails": "Εισαγάγετε στοιχεία κάρτας",
        "sheet.visaOrMastercard": "Visa ή Mastercard",
        "sheet.cardBrandsHint": "Visa ή Mastercard",
        "sheet.saveCardShort": "Αποθήκευση κάρτας για επόμενη φορά",
        "sheet.delete": "Διαγραφή",
        "sheet.edit": "Επεξεργασία",
        "sheet.done": "Τέλος",
        "sheet.removeCardConfirm": "Είστε βέβαιοι ότι θέλετε να αφαιρέσετε αυτή την κάρτα;",
        "sheet.remove": "Αφαίρεση",
        "sheet.keepIt": "Διατήρηση",
        "sheet.default": "Προεπιλογή",
        "sheet.authentication": "Ταυτοποίηση",
        "sheet.processingPayment": "Επεξεργασία πληρωμής...",
        "elements.cardNumber": "Αριθμός κάρτας",
        "elements.cardholderName": "Όνομα κατόχου",
        "elements.expDate": "Ημερομηνία λήξης",
        "elements.cvv": "CVV",
        "elements.saveCard": "Αποθήκευση κάρτας για μελλοντική χρήση",
        "elements.saveCardShort": "Αποθήκευση κάρτας για επόμενη φορά",
        "placeholder.cardNumber": "Αριθμός κάρτας",
        "placeholder.cardNumber.spaced": "1234 1234 1234 1234",
        "placeholder.expDate": "ΜΜ / ΕΕ",
        "placeholder.cvv": "CVV",
        "placeholder.cvv.spaced": "123",
        "placeholder.cardholderName": "Όνομα στην κάρτα",
        "errors.cardNumberRequired": "Ο αριθμός κάρτας είναι υποχρεωτικός.",
        "errors.cardNumberUnsupported": "Ο τύπος κάρτας δεν υποστηρίζεται.",
        "errors.cardNumberTooShort": "Ο αριθμός κάρτας είναι πολύ σύντομος.",
        "errors.cardNumberWrongLength": "Το μήκος του αριθμού κάρτας δεν είναι έγκυρο.",
        "errors.cardNumberInvalid": "Ο αριθμός κάρτας δεν είναι έγκυρος.",
        "errors.expDateRequired": "Η ημερομηνία λήξης είναι υποχρεωτική.",
        "errors.expDateInvalidFormat": "Η μορφή της ημερομηνίας λήξης δεν είναι έγκυρη.",
        "errors.expDateInvalidMonth": "Ο μήνας λήξης δεν είναι έγκυρος.",
        "errors.cardExpired": "Η κάρτα έχει λήξει.",
        "errors.cvvRequired": "Το CVV είναι υποχρεωτικό.",
        "errors.cvvInvalid": "Το CVV δεν είναι έγκυρο.",
        "errors.cardHolderNameRequired": "Το όνομα κατόχου είναι υποχρεωτικό.",
        "errors.cardHolderNameNoDigits": "Το όνομα κατόχου δεν μπορεί να περιέχει αριθμούς.",
        "errors.cardHolderNameInvalidChars": "Επιτρέπονται μόνο γράμματα, κενά, απόστροφοι, παύλες και τελείες.",
        "button.pay": "Πληρωμή {{amount}}",
        "button.payNoAmount": "Πληρωμή",
        "button.processing": "Επεξεργασία...",
        "button.book": "Κράτηση {{amount}}",
        "button.buy": "Αγορά {{amount}}",
        "button.checkout": "Ολοκλήρωση {{amount}}",
        "button.donate": "Δωρεά {{amount}}",
        "button.order": "Παραγγελία {{amount}}",
        "button.subscribe": "Συνδρομή {{amount}}",
        "button.topUp": "Φόρτιση {{amount}}",
        "button.deposit": "Κατάθεση {{amount}}",
    ]

    private static let ro: [String: String] = [
        "sheet.title": "Plată",
        "sheet.cancel": "Anulează",
        "sheet.creditDebitCard": "Card de credit / debit",
        "sheet.poweredBy": "Oferit de",
        "sheet.savedCards": "Carduri salvate",
        "sheet.payingWith": "Plată cu",
        "sheet.useAnotherCard": "Folosește alt card",
        "sheet.useOtherCard": "Folosește alt card",
        "sheet.or": "sau",
        "sheet.cardDetails": "Detalii card",
        "sheet.enterCardDetails": "Introduceți detaliile cardului",
        "sheet.visaOrMastercard": "Visa sau Mastercard",
        "sheet.cardBrandsHint": "Visa sau Mastercard",
        "sheet.saveCardShort": "Salvează cardul pentru data viitoare",
        "sheet.delete": "Șterge",
        "sheet.edit": "Editează",
        "sheet.done": "Gata",
        "sheet.removeCardConfirm": "Sigur doriți să eliminați acest card?",
        "sheet.remove": "Elimină",
        "sheet.keepIt": "Păstrează",
        "sheet.default": "Implicit",
        "sheet.authentication": "Autentificare",
        "sheet.processingPayment": "Se procesează plata...",
        "elements.cardNumber": "Număr card",
        "elements.cardholderName": "Numele titularului",
        "elements.expDate": "Data expirării",
        "elements.cvv": "CVV",
        "elements.saveCard": "Salvează cardul pentru utilizări viitoare",
        "elements.saveCardShort": "Salvează cardul pentru data viitoare",
        "placeholder.cardNumber": "Număr card",
        "placeholder.cardNumber.spaced": "1234 1234 1234 1234",
        "placeholder.expDate": "LL / AA",
        "placeholder.cvv": "CVV",
        "placeholder.cvv.spaced": "123",
        "placeholder.cardholderName": "Numele de pe card",
        "errors.cardNumberRequired": "Numărul cardului este obligatoriu.",
        "errors.cardNumberUnsupported": "Tipul de card nu este acceptat.",
        "errors.cardNumberTooShort": "Numărul cardului este prea scurt.",
        "errors.cardNumberWrongLength": "Lungimea numărului de card este invalidă.",
        "errors.cardNumberInvalid": "Numărul cardului este invalid.",
        "errors.expDateRequired": "Data expirării este obligatorie.",
        "errors.expDateInvalidFormat": "Formatul datei de expirare este invalid.",
        "errors.expDateInvalidMonth": "Luna de expirare este invalidă.",
        "errors.cardExpired": "Cardul a expirat.",
        "errors.cvvRequired": "CVV-ul este obligatoriu.",
        "errors.cvvInvalid": "CVV-ul este invalid.",
        "errors.cardHolderNameRequired": "Numele titularului este obligatoriu.",
        "errors.cardHolderNameNoDigits": "Numele titularului nu poate conține cifre.",
        "errors.cardHolderNameInvalidChars": "Sunt permise doar litere, spații, apostroafe, cratime și puncte.",
        "button.pay": "Plătește {{amount}}",
        "button.payNoAmount": "Plătește",
        "button.processing": "Se procesează...",
        "button.book": "Rezervă {{amount}}",
        "button.buy": "Cumpără {{amount}}",
        "button.checkout": "Finalizează {{amount}}",
        "button.donate": "Donează {{amount}}",
        "button.order": "Comandă {{amount}}",
        "button.subscribe": "Abonare {{amount}}",
        "button.topUp": "Alimentează {{amount}}",
        "button.deposit": "Depune {{amount}}",
    ]

    private static let bg: [String: String] = [
        "sheet.title": "Плащане",
        "sheet.cancel": "Отказ",
        "sheet.creditDebitCard": "Кредитна / дебитна карта",
        "sheet.poweredBy": "Предоставено от",
        "sheet.savedCards": "Запазени карти",
        "sheet.payingWith": "Плащане с",
        "sheet.useAnotherCard": "Използвай друга карта",
        "sheet.useOtherCard": "Използвай друга карта",
        "sheet.or": "или",
        "sheet.cardDetails": "Данни за картата",
        "sheet.enterCardDetails": "Въведете данни за картата",
        "sheet.visaOrMastercard": "Visa или Mastercard",
        "sheet.cardBrandsHint": "Visa или Mastercard",
        "sheet.saveCardShort": "Запази картата за следващия път",
        "sheet.delete": "Изтрий",
        "sheet.edit": "Редактирай",
        "sheet.done": "Готово",
        "sheet.removeCardConfirm": "Сигурни ли сте, че искате да премахнете тази карта?",
        "sheet.remove": "Премахни",
        "sheet.keepIt": "Запази я",
        "sheet.default": "По подразбиране",
        "sheet.authentication": "Удостоверяване",
        "sheet.processingPayment": "Обработка на плащането...",
        "elements.cardNumber": "Номер на картата",
        "elements.cardholderName": "Име на картодържателя",
        "elements.expDate": "Дата на валидност",
        "elements.cvv": "CVV",
        "elements.saveCard": "Запази картата за бъдеща употреба",
        "elements.saveCardShort": "Запази картата за следващия път",
        "placeholder.cardNumber": "Номер на картата",
        "placeholder.cardNumber.spaced": "1234 1234 1234 1234",
        "placeholder.expDate": "ММ / ГГ",
        "placeholder.cvv": "CVV",
        "placeholder.cvv.spaced": "123",
        "placeholder.cardholderName": "Име върху картата",
        "errors.cardNumberRequired": "Номерът на картата е задължителен.",
        "errors.cardNumberUnsupported": "Типът на картата не се поддържа.",
        "errors.cardNumberTooShort": "Номерът на картата е твърде кратък.",
        "errors.cardNumberWrongLength": "Дължината на номера на картата е невалидна.",
        "errors.cardNumberInvalid": "Номерът на картата е невалиден.",
        "errors.expDateRequired": "Датата на валидност е задължителна.",
        "errors.expDateInvalidFormat": "Форматът на датата на валидност е невалиден.",
        "errors.expDateInvalidMonth": "Месецът на валидност е невалиден.",
        "errors.cardExpired": "Картата е изтекла.",
        "errors.cvvRequired": "CVV е задължителен.",
        "errors.cvvInvalid": "CVV е невалиден.",
        "errors.cardHolderNameRequired": "Името на картодържателя е задължително.",
        "errors.cardHolderNameNoDigits": "Името на картодържателя не може да съдържа цифри.",
        "errors.cardHolderNameInvalidChars": "Разрешени са само букви, интервали, апострофи, тирета и точки.",
        "button.pay": "Плати {{amount}}",
        "button.payNoAmount": "Плати",
        "button.processing": "Обработка...",
        "button.book": "Резервирай {{amount}}",
        "button.buy": "Купи {{amount}}",
        "button.checkout": "Завърши поръчката {{amount}}",
        "button.donate": "Дари {{amount}}",
        "button.order": "Направи поръчка {{amount}}",
        "button.subscribe": "Абонирай се за {{amount}}",
        "button.topUp": "Зареди {{amount}}",
        "button.deposit": "Депозирай {{amount}}",
    ]

    private static let hu: [String: String] = [
        "sheet.title": "Fizetés",
        "sheet.cancel": "Mégse",
        "sheet.creditDebitCard": "Hitel- / bankkártya",
        "sheet.poweredBy": "Szolgáltató",
        "sheet.savedCards": "Mentett kártyák",
        "sheet.payingWith": "Fizetés ezzel",
        "sheet.useAnotherCard": "Másik kártya használata",
        "sheet.useOtherCard": "Másik kártya használata",
        "sheet.or": "vagy",
        "sheet.cardDetails": "Kártyaadatok",
        "sheet.enterCardDetails": "Adja meg a kártyaadatokat",
        "sheet.visaOrMastercard": "Visa vagy Mastercard",
        "sheet.cardBrandsHint": "Visa vagy Mastercard",
        "sheet.saveCardShort": "Kártya mentése a következő alkalomra",
        "sheet.delete": "Törlés",
        "sheet.edit": "Szerkesztés",
        "sheet.done": "Kész",
        "sheet.removeCardConfirm": "Biztosan eltávolítja ezt a kártyát?",
        "sheet.remove": "Eltávolítás",
        "sheet.keepIt": "Megtartás",
        "sheet.default": "Alapértelmezett",
        "sheet.authentication": "Hitelesítés",
        "sheet.processingPayment": "Fizetés feldolgozása...",
        "elements.cardNumber": "Kártyaszám",
        "elements.cardholderName": "Kártyabirtokos neve",
        "elements.expDate": "Lejárati dátum",
        "elements.cvv": "CVV",
        "elements.saveCard": "Kártya mentése későbbi használatra",
        "elements.saveCardShort": "Kártya mentése a következő alkalomra",
        "placeholder.cardNumber": "Kártyaszám",
        "placeholder.cardNumber.spaced": "1234 1234 1234 1234",
        "placeholder.expDate": "HH / ÉÉ",
        "placeholder.cvv": "CVV",
        "placeholder.cvv.spaced": "123",
        "placeholder.cardholderName": "Név a kártyán",
        "errors.cardNumberRequired": "A kártyaszám kötelező.",
        "errors.cardNumberUnsupported": "A kártyatípus nem támogatott.",
        "errors.cardNumberTooShort": "A kártyaszám túl rövid.",
        "errors.cardNumberWrongLength": "A kártyaszám hossza érvénytelen.",
        "errors.cardNumberInvalid": "A kártyaszám érvénytelen.",
        "errors.expDateRequired": "A lejárati dátum kötelező.",
        "errors.expDateInvalidFormat": "A lejárati dátum formátuma érvénytelen.",
        "errors.expDateInvalidMonth": "A lejárati hónap érvénytelen.",
        "errors.cardExpired": "A kártya lejárt.",
        "errors.cvvRequired": "A CVV kötelező.",
        "errors.cvvInvalid": "A CVV érvénytelen.",
        "errors.cardHolderNameRequired": "A kártyabirtokos neve kötelező.",
        "errors.cardHolderNameNoDigits": "A kártyabirtokos neve nem tartalmazhat számokat.",
        "errors.cardHolderNameInvalidChars": "Csak betűk, szóközök, aposztrófok, kötőjelek és pontok engedélyezettek.",
        "button.pay": "Fizetés {{amount}}",
        "button.payNoAmount": "Fizetés",
        "button.processing": "Feldolgozás...",
        "button.book": "Foglalás {{amount}}",
        "button.buy": "Vásárlás {{amount}}",
        "button.checkout": "Pénztár {{amount}}",
        "button.donate": "Adományozás {{amount}}",
        "button.order": "Rendelés leadása {{amount}}",
        "button.subscribe": "Előfizetés {{amount}} összegre",
        "button.topUp": "Feltöltés {{amount}}",
        "button.deposit": "Befizetés {{amount}}",
    ]

    private static let pl: [String: String] = [
        "sheet.title": "Płatność",
        "sheet.cancel": "Anuluj",
        "sheet.creditDebitCard": "Karta kredytowa / debetowa",
        "sheet.poweredBy": "Obsługiwane przez",
        "sheet.savedCards": "Zapisane karty",
        "sheet.payingWith": "Płatność za pomocą",
        "sheet.useAnotherCard": "Użyj innej karty",
        "sheet.useOtherCard": "Użyj innej karty",
        "sheet.or": "lub",
        "sheet.cardDetails": "Dane karty",
        "sheet.enterCardDetails": "Wprowadź dane karty",
        "sheet.visaOrMastercard": "Visa lub Mastercard",
        "sheet.cardBrandsHint": "Visa lub Mastercard",
        "sheet.saveCardShort": "Zapisz kartę na następnym razem",
        "sheet.delete": "Usuń",
        "sheet.edit": "Edytuj",
        "sheet.done": "Gotowe",
        "sheet.removeCardConfirm": "Czy na pewno chcesz usunąć tę kartę?",
        "sheet.remove": "Usuń",
        "sheet.keepIt": "Zachowaj",
        "sheet.default": "Domyślna",
        "sheet.authentication": "Uwierzytelnianie",
        "sheet.processingPayment": "Przetwarzanie płatności...",
        "elements.cardNumber": "Numer karty",
        "elements.cardholderName": "Imię i nazwisko posiadacza karty",
        "elements.expDate": "Data ważności",
        "elements.cvv": "CVV",
        "elements.saveCard": "Zapisz kartę do późniejszego użycia",
        "elements.saveCardShort": "Zapisz kartę na następnym razem",
        "placeholder.cardNumber": "Numer karty",
        "placeholder.cardNumber.spaced": "1234 1234 1234 1234",
        "placeholder.expDate": "MM / RR",
        "placeholder.cvv": "CVV",
        "placeholder.cvv.spaced": "123",
        "placeholder.cardholderName": "Imię i nazwisko na karcie",
        "errors.cardNumberRequired": "Numer karty jest wymagany.",
        "errors.cardNumberUnsupported": "Typ karty nie jest obsługiwany.",
        "errors.cardNumberTooShort": "Numer karty jest za krótki.",
        "errors.cardNumberWrongLength": "Długość numeru karty jest nieprawidłowa.",
        "errors.cardNumberInvalid": "Numer karty jest nieprawidłowy.",
        "errors.expDateRequired": "Data ważności jest wymagana.",
        "errors.expDateInvalidFormat": "Format daty ważności jest nieprawidłowy.",
        "errors.expDateInvalidMonth": "Miesiąc ważności jest nieprawidłowy.",
        "errors.cardExpired": "Karta wygasła.",
        "errors.cvvRequired": "CVV jest wymagany.",
        "errors.cvvInvalid": "CVV jest nieprawidłowy.",
        "errors.cardHolderNameRequired": "Imię i nazwisko posiadacza karty jest wymagane.",
        "errors.cardHolderNameNoDigits": "Imię i nazwisko posiadacza karty nie może zawierać cyfr.",
        "errors.cardHolderNameInvalidChars": "Dozwolone są tylko litery, spacje, apostrofy, myślniki i kropki.",
        "button.pay": "Zapłać {{amount}}",
        "button.payNoAmount": "Zapłać",
        "button.processing": "Przetwarzanie...",
        "button.book": "Zarezerwuj {{amount}}",
        "button.buy": "Kup {{amount}}",
        "button.checkout": "Finalizuj zamówienie {{amount}}",
        "button.donate": "Przekaż darowiznę {{amount}}",
        "button.order": "Złóż zamówienie {{amount}}",
        "button.subscribe": "Subskrybuj za {{amount}}",
        "button.topUp": "Doładuj {{amount}}",
        "button.deposit": "Wpłać {{amount}}",
    ]
}
